### ISSUE TITLE
Quite a novel project! 😆

### ISSUE THREAD

**Issue by joshuaquek** [issue-db/issue-db#3]
quite a cool project!

I'm building something similar that allows one to use Google Sheets as a Database:

https://github.com/joshuaquek/secure-googlesheets-db

**Comment by zeke** [comment]
Thanks for the kind words. :)

> Google Sheets as a Database

That's a great idea. I've tried to find npm modules to interact with Google Sheets before, and they all seem overcomplicated or broken. It would be great to have a simple interface.

**Comment by zeke** [comment]
Gonna close this out, but feel free to keep me posted on your project.

**Comment by joshuaquek** [comment]
Sure! :D
